### ISSUE TITLE
[FEATURE] Mod Form and Spreadsheet Integration using an API

### ISSUE THREAD

**Issue by KendrickLamar2003** [Cartrigger/QCXRsoonbot#27]
### 📂 What category is this feature in?

Information

### 📝 Description of Feature

Form: https://forms.gle/hVZNRVjh2rykG41g6
Spreadsheet: https://docs.google.com/spreadsheets/d/12yUTO_HgAEyZFoETxmzqaxPZrOUF1ocaQjbi_u5U2jI/edit?usp=sharing

It also sorta relates to https://github.com/Cartrigger/QCXRSoonBot/pull/26

**Comment by TecEash1** [comment]
Swaggio do you think this should still be added following the update with mod compatibility to qc?

**Comment by TecEash1** [comment]
> Swaggio do you think this should still be added following the update with mod compatibility to qc?

- wait u put what renderers work, that might be useful, also should we make it only include mods that don't work? Most mods work for qc in general.
